In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

device = torch.device("mps")
print(f"Using {device} device")

Using mps device


In [4]:
# Hyperparameters
embed_dim = 64 # 64 x 64 image
artist_dim = 16 # 16 possible artists
learning_rate = 0.001
num_epochs = 10

In [5]:
# Generate a 64 x 64 input image
input_image = torch.randn(1, 64, 64).to(device)
# Generate a artist ID
artist_id = torch.zeros(artist_dim).to(device)
artist_id[1] = 1

In [6]:
input_image.dim()
print(input_image)
print(artist_id)

tensor([[[ 0.2517, -1.2288, -1.7048,  ...,  0.1768, -0.2774, -0.4109],
         [ 0.2052,  0.9750, -0.4243,  ...,  0.4532,  0.8703,  1.2603],
         [ 0.9839,  0.3851, -0.6078,  ..., -1.6633, -0.0301, -1.1787],
         ...,
         [-1.4937, -1.2528,  0.0419,  ...,  0.9036,  0.0149, -0.3086],
         [ 0.4303, -1.9189,  0.3784,  ..., -0.6111,  0.0541,  1.7902],
         [-0.6429, -0.8082,  0.2575,  ..., -2.5848, -1.4193,  0.1057]]],
       device='mps:0')
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='mps:0')


In [7]:
class ImageEmbedding(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, embed_dim, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )

    def forward(self, x):
        return self.conv(x)


In [8]:
m = ImageEmbedding(embed_dim).to(device)
print(m)

res = m(input_image)

print(len(res))
print(res.dim())
print(res)


ImageEmbedding(
  (conv): Sequential(
    (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
)
64
3
tensor([[[0.5449, 0.9756, 0.8772,  ..., 0.3411, 0.2852, 0.3611],
         [0.2681, 0.5675, 0.5638,  ..., 0.6870, 0.2934, 1.1321],
         [0.9072, 1.0035, 0.5946,  ..., 0.6802, 0.4653, 0.4922],
         ...,
         [0.8770, 0.4631, 0.9029,  ..., 0.6145, 0.5975, 0.5756],
         [0.6803, 1.3046, 0.3726,  ..., 0.7545, 0.2217, 0.3648],
         [0.5720, 0.7174, 0.7419,  ..., 0.8516, 0.5946, 1.2944]],

        [[0.5184, 0.0000, 0.9926,  ..., 0.5968, 0.3924, 0.4255],
         [0.4555, 0.5844, 2.0218,  ..., 0.2160, 1.2917, 0.2613],
         [1.5109, 0.2495, 0.2419,  ..., 0.0000, 0.9158, 0.2969],
         ...,
         [0.1404, 0.1925, 0.0033,  ..., 1.6884, 0.8359, 0.8336],
         [0.5497, 0.6573, 1.0921,  ..., 0.0719, 1.2262, 0.9499],
         [0.3351, 0.9041, 0.6119

In [9]:
model = nn.Sequential(
    nn.Linear(embed_dim, 256),
    nn.ReLU(),
    nn.Linear(256, artist_dim),
    nn.ReLU()
).to(device)


In [10]:
res = model(input_image)
print("res =", res)
print(res.dim())
print(len(res), len(res[0]), len(res[0][0]))

# get max
max = res.argmax()
print(max)

res = tensor([[[0.0139, 0.4442, 0.1653,  ..., 0.0000, 0.3983, 0.0000],
         [0.1846, 0.0740, 0.4065,  ..., 0.0669, 0.1329, 0.0848],
         [0.4377, 0.0999, 0.0000,  ..., 0.0330, 0.0891, 0.4632],
         ...,
         [0.0438, 0.1077, 0.2411,  ..., 0.0000, 0.4372, 0.0185],
         [0.0000, 0.0000, 0.1918,  ..., 0.3044, 0.0367, 0.1270],
         [0.2751, 0.0500, 0.3544,  ..., 0.0000, 0.0000, 0.0439]]],
       device='mps:0', grad_fn=<ReluBackward0>)
3
1 64 16
tensor(35, device='mps:0')


In [13]:
res[0][35]

tensor([0.4539, 0.0000, 0.0000, 0.0876, 0.0000, 0.0000, 0.0925, 0.1116, 0.0000,
        0.0000, 0.0000, 0.2526, 0.1111, 0.1165, 0.2321, 0.0241],
       device='mps:0', grad_fn=<SelectBackward0>)

In [ ]:
## Testing

# pool of square window of size=3, stride=2
m = nn.MaxPool2d(3, stride=2)
print(m)
input_image = torch.randn(1, 3, 64, 64).to(device)
print(input_image.dim())
output = m(input_image)

print(output.dim())